//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notification
{
    using System;
    using System.Runtime.Serialization;
    using Notification.Model;

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApplicationContext", Namespace="http://schemas.datacontract.org/2004/07/Tavisca.NotificationService.DataContracts" +
        "")]
    public partial class ApplicationContext : object
    {
        
        private Notification.KeyValuePair[] AdditionalDataField;
        
        private string ApplicationNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Notification.KeyValuePair[] AdditionalData
        {
            get
            {
                return this.AdditionalDataField;
            }
            set
            {
                this.AdditionalDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationName
        {
            get
            {
                return this.ApplicationNameField;
            }
            set
            {
                this.ApplicationNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KeyValuePair", Namespace="http://schemas.datacontract.org/2004/07/Tavisca.NotificationService.DataContracts" +
        "")]
    public partial class KeyValuePair : object
    {
        
        private string KeyField;
        
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key
        {
            get
            {
                return this.KeyField;
            }
            set
            {
                this.KeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Message", Namespace="http://Tavisca.NotificationService.DataContracts/2007/11")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Notification.MailMessage))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Notification.TemplateMessage))]
    public partial class Message : object
    {
        
        private System.Guid IdField;
        
        private string FromField;
        
        private string[] ToField;
        
        private string[] CCField;
        
        private string[] BCCField;
        
        private string SubjectField;
        
        private Notification.DeliveryStatus StatusField;
        
        private System.DateTime SentDateField;
        
        private string[] TagsField;
        
        public Notification.Attachment[] AttachmentsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string From
        {
            get
            {
                return this.FromField;
            }
            set
            {
                this.FromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string[] To
        {
            get
            {
                return this.ToField;
            }
            set
            {
                this.ToField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string[] CC
        {
            get
            {
                return this.CCField;
            }
            set
            {
                this.CCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string[] BCC
        {
            get
            {
                return this.BCCField;
            }
            set
            {
                this.BCCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string Subject
        {
            get
            {
                return this.SubjectField;
            }
            set
            {
                this.SubjectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public Notification.DeliveryStatus Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public System.DateTime SentDate
        {
            get
            {
                return this.SentDateField;
            }
            set
            {
                this.SentDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string[] Tags
        {
            get
            {
                return this.TagsField;
            }
            set
            {
                this.TagsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public Notification.Attachment[] Attachments
        {
            get
            {
                return this.AttachmentsField;
            }
            set
            {
                this.AttachmentsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MailMessage", Namespace="http://Tavisca.NotificationService.DataContracts/2007/11")]
    public partial class MailMessage : Notification.Message
    {
        
        private string BodyField;
        
        private bool IsHtmlField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Body
        {
            get
            {
                return this.BodyField;
            }
            set
            {
                this.BodyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsHtml
        {
            get
            {
                return this.IsHtmlField;
            }
            set
            {
                this.IsHtmlField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TemplateMessage", Namespace="http://schemas.datacontract.org/2004/07/Tavisca.NotificationService.DataContracts" +
        "")]
    public partial class TemplateMessage : Notification.Message
    {
        
        private Notification.KeyValuePair[] TemplateAttributesField;
        
        private string TemplateNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Notification.KeyValuePair[] TemplateAttributes
        {
            get
            {
                return this.TemplateAttributesField;
            }
            set
            {
                this.TemplateAttributesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TemplateName
        {
            get
            {
                return this.TemplateNameField;
            }
            set
            {
                this.TemplateNameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeliveryStatus", Namespace="http://schemas.datacontract.org/2004/07/Tavisca.NotificationService.DataContracts" +
        "")]
    public enum DeliveryStatus : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        All = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sent = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SentSuccessful = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FailureRetry = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failed = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Attachment", Namespace="http://Tavisca.NotificationService.DataContracts/2007/11")]
    public partial class Attachment : object
    {
        
        private string FileNameField;
        
        private string FileExtensionField;
        
        private byte[] AttachmentFileField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName
        {
            get
            {
                return this.FileNameField;
            }
            set
            {
                this.FileNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string FileExtension
        {
            get
            {
                return this.FileExtensionField;
            }
            set
            {
                this.FileExtensionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public byte[] AttachmentFile
        {
            get
            {
                return this.AttachmentFileField;
            }
            set
            {
                this.AttachmentFileField = value;
            }
        }

        public static explicit operator Attachment(AttachmentData v)
        {
            throw new NotImplementedException();
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DefaultFaultContract", Namespace="http://Tavisca.NotificationService.FaultContracts/2007/11")]
    public partial class DefaultFaultContract : object
    {
        
        private int ErrorIdField;
        
        private string ErrorMessageField;
        
        private System.Guid CorrelationIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ErrorId
        {
            get
            {
                return this.ErrorIdField;
            }
            set
            {
                this.ErrorIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Guid CorrelationId
        {
            get
            {
                return this.CorrelationIdField;
            }
            set
            {
                this.CorrelationIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Criteria", Namespace="http://Tavisca.NotificationService.DataContracts/2007/11")]
    public partial class Criteria : object
    {
        
        private bool DatesSpecifiedField;
        
        private System.DateTime StartDateField;
        
        private System.DateTime EndDateField;
        
        private string SubjectField;
        
        private string BodyField;
        
        private string[] ToField;
        
        private string[] FromField;
        
        private string[] CCField;
        
        private string[] BCCField;
        
        private System.Guid[] MessageIdField;
        
        private Notification.PageDetail PageDetailField;
        
        private string[] TagsField;
        
        private Notification.TagOperation TagOperationField;
        
        private bool ApplyTagFilterField;
        
        private Notification.DeliveryStatus StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool DatesSpecified
        {
            get
            {
                return this.DatesSpecifiedField;
            }
            set
            {
                this.DatesSpecifiedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate
        {
            get
            {
                return this.StartDateField;
            }
            set
            {
                this.StartDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime EndDate
        {
            get
            {
                return this.EndDateField;
            }
            set
            {
                this.EndDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Subject
        {
            get
            {
                return this.SubjectField;
            }
            set
            {
                this.SubjectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Body
        {
            get
            {
                return this.BodyField;
            }
            set
            {
                this.BodyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string[] To
        {
            get
            {
                return this.ToField;
            }
            set
            {
                this.ToField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string[] From
        {
            get
            {
                return this.FromField;
            }
            set
            {
                this.FromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string[] CC
        {
            get
            {
                return this.CCField;
            }
            set
            {
                this.CCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string[] BCC
        {
            get
            {
                return this.BCCField;
            }
            set
            {
                this.BCCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public System.Guid[] MessageId
        {
            get
            {
                return this.MessageIdField;
            }
            set
            {
                this.MessageIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public Notification.PageDetail PageDetail
        {
            get
            {
                return this.PageDetailField;
            }
            set
            {
                this.PageDetailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string[] Tags
        {
            get
            {
                return this.TagsField;
            }
            set
            {
                this.TagsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public Notification.TagOperation TagOperation
        {
            get
            {
                return this.TagOperationField;
            }
            set
            {
                this.TagOperationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public bool ApplyTagFilter
        {
            get
            {
                return this.ApplyTagFilterField;
            }
            set
            {
                this.ApplyTagFilterField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public Notification.DeliveryStatus Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PageDetail", Namespace="http://schemas.datacontract.org/2004/07/Tavisca.NotificationService.DataContracts" +
        "")]
    public partial class PageDetail : object
    {
        
        private int PageNumberField;
        
        private int PageSizeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageNumber
        {
            get
            {
                return this.PageNumberField;
            }
            set
            {
                this.PageNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageSize
        {
            get
            {
                return this.PageSizeField;
            }
            set
            {
                this.PageSizeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TagOperation", Namespace="http://schemas.datacontract.org/2004/07/Tavisca.NotificationService.DataContracts" +
        "")]
    public enum TagOperation : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Or = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        And = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageList", Namespace="http://Tavisca.NotificationService.DataContracts/2007/11")]
    public partial class MessageList : object
    {
        
        private Notification.Message[] MessagesField;
        
        private Notification.PagingInfo PagingInfoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Notification.Message[] Messages
        {
            get
            {
                return this.MessagesField;
            }
            set
            {
                this.MessagesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Notification.PagingInfo PagingInfo
        {
            get
            {
                return this.PagingInfoField;
            }
            set
            {
                this.PagingInfoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PagingInfo", Namespace="http://schemas.datacontract.org/2004/07/Tavisca.NotificationService.DataContracts" +
        "")]
    public partial class PagingInfo : object
    {
        
        private int PageNumberField;
        
        private int PageSizeField;
        
        private int TotalResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageNumber
        {
            get
            {
                return this.PageNumberField;
            }
            set
            {
                this.PageNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageSize
        {
            get
            {
                return this.PageSizeField;
            }
            set
            {
                this.PageSizeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalResult
        {
            get
            {
                return this.TotalResultField;
            }
            set
            {
                this.TotalResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageInfoList", Namespace="http://Tavisca.NotificationService.DataContracts/2008/11")]
    public partial class MessageInfoList : object
    {
        
        private Notification.MessageInfo[] MessagesField;
        
        private Notification.PagingInfo PagingInfoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Notification.MessageInfo[] Messages
        {
            get
            {
                return this.MessagesField;
            }
            set
            {
                this.MessagesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Notification.PagingInfo PagingInfo
        {
            get
            {
                return this.PagingInfoField;
            }
            set
            {
                this.PagingInfoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageInfo", Namespace="http://Tavisca.NotificationService.DataContracts/2008/11")]
    public partial class MessageInfo : object
    {
        
        private System.Guid IdField;
        
        private string FromField;
        
        private string[] ToField;
        
        private string[] CCField;
        
        private string[] BCCField;
        
        private string SubjectField;
        
        private Notification.DeliveryStatus StatusField;
        
        private System.DateTime SentDateField;
        
        private string[] TagsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string From
        {
            get
            {
                return this.FromField;
            }
            set
            {
                this.FromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string[] To
        {
            get
            {
                return this.ToField;
            }
            set
            {
                this.ToField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string[] CC
        {
            get
            {
                return this.CCField;
            }
            set
            {
                this.CCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string[] BCC
        {
            get
            {
                return this.BCCField;
            }
            set
            {
                this.BCCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string Subject
        {
            get
            {
                return this.SubjectField;
            }
            set
            {
                this.SubjectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public Notification.DeliveryStatus Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public System.DateTime SentDate
        {
            get
            {
                return this.SentDateField;
            }
            set
            {
                this.SentDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string[] Tags
        {
            get
            {
                return this.TagsField;
            }
            set
            {
                this.TagsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TagList", Namespace="http://schemas.datacontract.org/2004/07/Tavisca.NotificationService.DataContracts" +
        "")]
    public partial class TagList : object
    {
        
        private string[] TagsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Tags
        {
            get
            {
                return this.TagsField;
            }
            set
            {
                this.TagsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Template", Namespace="http://schemas.datacontract.org/2004/07/Tavisca.NotificationService.DataContracts" +
        "")]
    public partial class Template : object
    {
        
        private Notification.KeyValuePair[] AdditionalDataField;
        
        private string BodyField;
        
        private string DescriptionField;
        
        private bool IsHtmlField;
        
        private string NameField;
        
        private Notification.TemplateTag[] TagsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Notification.KeyValuePair[] AdditionalData
        {
            get
            {
                return this.AdditionalDataField;
            }
            set
            {
                this.AdditionalDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Body
        {
            get
            {
                return this.BodyField;
            }
            set
            {
                this.BodyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsHtml
        {
            get
            {
                return this.IsHtmlField;
            }
            set
            {
                this.IsHtmlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Notification.TemplateTag[] Tags
        {
            get
            {
                return this.TagsField;
            }
            set
            {
                this.TagsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TemplateTag", Namespace="http://schemas.datacontract.org/2004/07/Tavisca.NotificationService.DataContracts" +
        "")]
    public partial class TemplateTag : object
    {
        
        private string DescriptionField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TemplateList", Namespace="http://schemas.datacontract.org/2004/07/Tavisca.NotificationService.DataContracts" +
        "")]
    public partial class TemplateList : object
    {
        
        private Notification.TemplateInfo[] TemplatesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Notification.TemplateInfo[] Templates
        {
            get
            {
                return this.TemplatesField;
            }
            set
            {
                this.TemplatesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TemplateInfo", Namespace="http://schemas.datacontract.org/2004/07/Tavisca.NotificationService.DataContracts" +
        "")]
    public partial class TemplateInfo : object
    {
        
        private string BodyField;
        
        private string DescriptionField;
        
        private bool IsHtmlField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Body
        {
            get
            {
                return this.BodyField;
            }
            set
            {
                this.BodyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsHtml
        {
            get
            {
                return this.IsHtmlField;
            }
            set
            {
                this.IsHtmlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Tavisca.NotificationService.ServiceContracts/2007/11", ConfigurationName="Notification.IMail")]
    public interface IMail
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="SendMail", ReplyAction="http://Tavisca.NotificationService.ServiceContracts/2007/11/IMail/SendMailRespons" +
            "e")]
        [System.ServiceModel.FaultContractAttribute(typeof(Notification.DefaultFaultContract), Action="http://Tavisca.NotificationService.ServiceContracts/2007/11/IMail/SendMailDefault" +
            "FaultContractFault", Name="DefaultFaultContract", Namespace="http://Tavisca.NotificationService.FaultContracts/2007/11")]
        System.Threading.Tasks.Task<System.Guid> SendMailAsync(Notification.ApplicationContext applicationContext, Notification.Message message);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetMails", ReplyAction="http://Tavisca.NotificationService.ServiceContracts/2007/11/IMail/GetMailsRespons" +
            "e")]
        [System.ServiceModel.FaultContractAttribute(typeof(Notification.DefaultFaultContract), Action="http://Tavisca.NotificationService.ServiceContracts/2007/11/IMail/GetMailsDefault" +
            "FaultContractFault", Name="DefaultFaultContract", Namespace="http://Tavisca.NotificationService.FaultContracts/2007/11")]
        System.Threading.Tasks.Task<Notification.MessageList> GetMailsAsync(Notification.ApplicationContext applicationContext, Notification.Criteria criteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetMailsInfo", ReplyAction="http://Tavisca.NotificationService.ServiceContracts/2007/11/IMail/GetMailsInfoRes" +
            "ponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Notification.DefaultFaultContract), Action="http://Tavisca.NotificationService.ServiceContracts/2007/11/IMail/GetMailsInfoDef" +
            "aultFaultContractFault", Name="DefaultFaultContract", Namespace="http://Tavisca.NotificationService.FaultContracts/2007/11")]
        System.Threading.Tasks.Task<Notification.MessageInfoList> GetMailsInfoAsync(Notification.ApplicationContext applicationContext, Notification.Criteria criteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetTags", ReplyAction="http://Tavisca.NotificationService.ServiceContracts/2007/11/IMail/GetTagsResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(Notification.DefaultFaultContract), Action="http://Tavisca.NotificationService.ServiceContracts/2007/11/IMail/GetTagsDefaultF" +
            "aultContractFault", Name="DefaultFaultContract", Namespace="http://Tavisca.NotificationService.FaultContracts/2007/11")]
        System.Threading.Tasks.Task<Notification.TagList> GetTagsAsync(Notification.ApplicationContext applicationContext);
        
        [System.ServiceModel.OperationContractAttribute(Action="ResendMail", ReplyAction="http://Tavisca.NotificationService.ServiceContracts/2007/11/IMail/ResendMailRespo" +
            "nse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Notification.DefaultFaultContract), Action="http://Tavisca.NotificationService.ServiceContracts/2007/11/IMail/ResendMailDefau" +
            "ltFaultContractFault", Name="DefaultFaultContract", Namespace="http://Tavisca.NotificationService.FaultContracts/2007/11")]
        System.Threading.Tasks.Task ResendMailAsync(Notification.ApplicationContext applicationContext, System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="CreateTemplate", ReplyAction="http://Tavisca.NotificationService.ServiceContracts/2007/11/IMail/CreateTemplateR" +
            "esponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Notification.DefaultFaultContract), Action="http://Tavisca.NotificationService.ServiceContracts/2007/11/IMail/CreateTemplateD" +
            "efaultFaultContractFault", Name="DefaultFaultContract", Namespace="http://Tavisca.NotificationService.FaultContracts/2007/11")]
        System.Threading.Tasks.Task CreateTemplateAsync(Notification.ApplicationContext applicationContext, Notification.Template template);
        
        [System.ServiceModel.OperationContractAttribute(Action="DeleteTemplate", ReplyAction="http://Tavisca.NotificationService.ServiceContracts/2007/11/IMail/DeleteTemplateR" +
            "esponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Notification.DefaultFaultContract), Action="http://Tavisca.NotificationService.ServiceContracts/2007/11/IMail/DeleteTemplateD" +
            "efaultFaultContractFault", Name="DefaultFaultContract", Namespace="http://Tavisca.NotificationService.FaultContracts/2007/11")]
        System.Threading.Tasks.Task DeleteTemplateAsync(Notification.ApplicationContext applicationContext, string templateName);
        
        [System.ServiceModel.OperationContractAttribute(Action="UpdateTemplate", ReplyAction="http://Tavisca.NotificationService.ServiceContracts/2007/11/IMail/UpdateTemplateR" +
            "esponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Notification.DefaultFaultContract), Action="http://Tavisca.NotificationService.ServiceContracts/2007/11/IMail/UpdateTemplateD" +
            "efaultFaultContractFault", Name="DefaultFaultContract", Namespace="http://Tavisca.NotificationService.FaultContracts/2007/11")]
        System.Threading.Tasks.Task UpdateTemplateAsync(Notification.ApplicationContext applicationContext, string templateName, Notification.Template template);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetTemplate", ReplyAction="http://Tavisca.NotificationService.ServiceContracts/2007/11/IMail/GetTemplateResp" +
            "onse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Notification.DefaultFaultContract), Action="http://Tavisca.NotificationService.ServiceContracts/2007/11/IMail/GetTemplateDefa" +
            "ultFaultContractFault", Name="DefaultFaultContract", Namespace="http://Tavisca.NotificationService.FaultContracts/2007/11")]
        System.Threading.Tasks.Task<Notification.Template> GetTemplateAsync(Notification.ApplicationContext applicationContext, string templateName);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetTemplates", ReplyAction="http://Tavisca.NotificationService.ServiceContracts/2007/11/IMail/GetTemplatesRes" +
            "ponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Notification.DefaultFaultContract), Action="http://Tavisca.NotificationService.ServiceContracts/2007/11/IMail/GetTemplatesDef" +
            "aultFaultContractFault", Name="DefaultFaultContract", Namespace="http://Tavisca.NotificationService.FaultContracts/2007/11")]
        System.Threading.Tasks.Task<Notification.TemplateList> GetTemplatesAsync(Notification.ApplicationContext applicationContext);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetResolvedMessage", ReplyAction="http://Tavisca.NotificationService.ServiceContracts/2007/11/IMail/GetResolvedMess" +
            "ageResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Notification.DefaultFaultContract), Action="http://Tavisca.NotificationService.ServiceContracts/2007/11/IMail/GetResolvedMess" +
            "ageDefaultFaultContractFault", Name="DefaultFaultContract", Namespace="http://Tavisca.NotificationService.FaultContracts/2007/11")]
        System.Threading.Tasks.Task<Notification.MailMessage> GetResolvedMessageAsync(Notification.ApplicationContext applicationContext, Notification.TemplateMessage templateMessage);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public interface IMailChannel : Notification.IMail, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public partial class MailClient : System.ServiceModel.ClientBase<Notification.IMail>, Notification.IMail
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MailClient() : 
                base(MailClient.GetDefaultBinding(), MailClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IMail.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MailClient(EndpointConfiguration endpointConfiguration) : 
                base(MailClient.GetBindingForEndpoint(endpointConfiguration), MailClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MailClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MailClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MailClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MailClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MailClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<System.Guid> SendMailAsync(Notification.ApplicationContext applicationContext, Notification.Message message)
        {
            return base.Channel.SendMailAsync(applicationContext, message);
        }
        
        public System.Threading.Tasks.Task<Notification.MessageList> GetMailsAsync(Notification.ApplicationContext applicationContext, Notification.Criteria criteria)
        {
            return base.Channel.GetMailsAsync(applicationContext, criteria);
        }
        
        public System.Threading.Tasks.Task<Notification.MessageInfoList> GetMailsInfoAsync(Notification.ApplicationContext applicationContext, Notification.Criteria criteria)
        {
            return base.Channel.GetMailsInfoAsync(applicationContext, criteria);
        }
        
        public System.Threading.Tasks.Task<Notification.TagList> GetTagsAsync(Notification.ApplicationContext applicationContext)
        {
            return base.Channel.GetTagsAsync(applicationContext);
        }
        
        public System.Threading.Tasks.Task ResendMailAsync(Notification.ApplicationContext applicationContext, System.Guid id)
        {
            return base.Channel.ResendMailAsync(applicationContext, id);
        }
        
        public System.Threading.Tasks.Task CreateTemplateAsync(Notification.ApplicationContext applicationContext, Notification.Template template)
        {
            return base.Channel.CreateTemplateAsync(applicationContext, template);
        }
        
        public System.Threading.Tasks.Task DeleteTemplateAsync(Notification.ApplicationContext applicationContext, string templateName)
        {
            return base.Channel.DeleteTemplateAsync(applicationContext, templateName);
        }
        
        public System.Threading.Tasks.Task UpdateTemplateAsync(Notification.ApplicationContext applicationContext, string templateName, Notification.Template template)
        {
            return base.Channel.UpdateTemplateAsync(applicationContext, templateName, template);
        }
        
        public System.Threading.Tasks.Task<Notification.Template> GetTemplateAsync(Notification.ApplicationContext applicationContext, string templateName)
        {
            return base.Channel.GetTemplateAsync(applicationContext, templateName);
        }
        
        public System.Threading.Tasks.Task<Notification.TemplateList> GetTemplatesAsync(Notification.ApplicationContext applicationContext)
        {
            return base.Channel.GetTemplatesAsync(applicationContext);
        }
        
        public System.Threading.Tasks.Task<Notification.MailMessage> GetResolvedMessageAsync(Notification.ApplicationContext applicationContext, Notification.TemplateMessage templateMessage)
        {
            return base.Channel.GetResolvedMessageAsync(applicationContext, templateMessage);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMail))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMail))
            {
                return new System.ServiceModel.EndpointAddress("http://apis.dev-worldventures.biz/Vexiere/V2.0/NotificationService/Mail.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return MailClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IMail);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return MailClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IMail);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IMail,
        }
    }
}
